modLoader="javafml"
loaderVersion="[25,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/HudCompass/issues"
displayURL="https://github.com/gigaherz/HudCompass"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[mods]]
modId="hudcompass"
version="${version}"
displayName="HUD Compass"
description='''
Declutter your inventory of tools
'''

[[dependencies.toolbelt]]
   modId="forge"
   mandatory=true
   versionRange="[26.0.12,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.2,1.15)"
   ordering="NONE"
   side="BOTH"