modLoader="javafml"
loaderVersion="[34,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/HudCompass/issues"

[[mods]]
modId="hudcompass"
version="${version}"
displayName="HUD Compass"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"
displayURL="https://github.com/gigaherz/HudCompass"
#updateJSONURL="http://myurl.me/"
description='''
See where you go
'''

[[dependencies.hudcompass]]
   modId="forge"
   mandatory=true
   versionRange="[34.1.22,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.3,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.hudcompass]]
   modId="xaerominimap"
   mandatory=false
   versionRange="[21.12.5,)"
   ordering="NONE"
   side="BOTH"